"""
Mock Packager Agent
Merges metadata and assets into final ZIP bundle
"""

import asyncio
import zipfile
from typing import Dict, Any, Callable
from pathlib import Path
from datetime import datetime
from app.logger import setup_logger
from app.settings import settings

logger = setup_logger(__name__)


class MockPackagerAgent:
    """Mock packager - creates real ZIP files with mock assets"""

    async def execute(
        self,
        bundle_dir: Path,
        plan_data: Dict[str, Any],
        assets_data: Dict[str, Any],
        emit: Callable[[Dict[str, Any]], None]
    ) -> Path:
        """Execute packaging step"""

        # Emit progress
        for pct in [0, 25, 50, 75, 100]:
            emit({"event": "progress", "step": "Packager", "pct": pct})
            await asyncio.sleep(0.3)

        # Create output ZIP
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = settings.output_dir / f"bundle_{timestamp}.zip"

        with zipfile.ZipFile(output_file, 'w', zipfile.ZIP_DEFLATED) as zf:
            # Add assets
            assets_dir = bundle_dir / "assets"
            if assets_dir.exists():
                for asset_file in assets_dir.iterdir():
                    if asset_file.is_file():
                        zf.write(asset_file, f"assets/{asset_file.name}")

            # Add metadata files
            import orjson

            # Etsy metadata
            etsy_data = assets_data["metadata"]["etsy"]
            zf.writestr("metadata/etsy.json", orjson.dumps(etsy_data, option=orjson.OPT_INDENT_2))

            # Gumroad metadata
            gumroad_data = assets_data["metadata"]["gumroad"]
            zf.writestr("metadata/gumroad.json", orjson.dumps(gumroad_data, option=orjson.OPT_INDENT_2))

            # Add QA report
            qa_report = assets_data["qa_report"]
            zf.writestr("QA_REPORT.json", orjson.dumps(qa_report, option=orjson.OPT_INDENT_2))

            # Add README
            readme_content = f"""# {plan_data['title']}

## Description
{plan_data['description']}

## Contents
{len(assets_data['generated_assets'])} digital assets

## Pricing
- Base: ${plan_data['pricing']['base_price']}
- Suggested: ${plan_data['pricing']['suggested_price']}
- Premium: ${plan_data['pricing']['premium_price']}

## Target Audience
{plan_data['target_persona']['occupation']}

## Marketplaces
- Etsy
- Gumroad

## QA Score
{qa_report['score'] * 100:.0f}% - {qa_report['status'].upper()}

Generated by AssetForge (MOCK MODE) on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
            zf.writestr("README.md", readme_content)

        logger.info(f"[MOCK] Package created: {output_file}")
        return output_file
